import type { Metadata } from "next";
import { Maven_Pro } from "next/font/google";
import "@/public/css/globals.css";
import { Header } from "./components/Header";
import "swiper/css";
import Footer from "./components/Footer";
import { getDictionary } from "@/get-dictionary";
import type { Locale } from "@/i18n-config";

const mavenPro = Maven_Pro({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Ronaldo MINE",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: { lang: string };
}>) {
  const dict = await getDictionary(params.lang as Locale);

  return (
    <html lang={params.lang}>
      <body className={mavenPro.className}>
        <main className="px-5 sm:px-10 max-w-6xl mx-auto pb-10">
          <Header lang={params.lang} dict={dict.header} />
          {children}
          <Footer dict={dict.footer} lang={params.lang} contactText={dict.contactButton} />
        </main>
      </body>
    </html>
  );
}
